<?php $__env->startSection('content'); ?>
<div id="main-content">
    <div class="page-heading">
        <div class="page-code">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3>Developers</h3>
                    <p class="text-subcode text-muted">View and manage all developer options.</p>
                </div>
            </div>
        </div>
        
    </div>

    <section class="section">
        <div class="card">
            <div class="card-header">
                <h4 class="card-code">Cache the Application Routes</h4>
            </div>
            <div class="card-body">
                <p>After adding a new feature that includes routes, remember to run <code>php artisan route:cache</code>, as the app may not automatically detect new routes.</p>
                
                <div class="row">
                    <div class="text-end">
                        <form action="<?php echo e(route('cache.routes')); ?>" method="POST">
                            <?php echo csrf_field(); ?>
                            <button type="submit" class="btn btn-sm btn-primary">
                                Cache now
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h4 class="card-code">Reset and Seed Database with Dummy Data</h4>
            </div>
            <div class="card-body">
                <p>This will execute the command <code>php artisan migrate:fresh --seed</code>, which will delete the entire database and create dummy data.</p>
                
                <div class="row">
                    <div class="text-end">
                        <form action="<?php echo e(route('database.migrate.fresh.seed')); ?>" method="POST">
                            <?php echo csrf_field(); ?>
                            <button type="submit" class="btn btn-sm btn-primary">
                                Execute now
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>            
    </section>

    <section class="section">
        <div class="card">
            <div class="card-header">
                <h4 class="card-code">Laravel Log Viewer</h4>
            </div>
            <div class="card-body">
                <p>A functionality that provides you with the ability to view and monitor the logs generated by your Laravel application, allowing for easier debugging and tracking of system activities.</p>
                
                <div class="row">
                    <div class="text-end">
                        <a href="<?php echo e(url('/backend/log-viewer')); ?>" class="btn btn-sm btn-primary" target="_blank">Go Now</a>
                    </div>
                </div>
            </div>
        </div> 
    </section>

    <section class="section">
        <div class="card">
            <div class="card-header">
                <h4 class="card-code">
                    Laravel Seed Or Factory Runner [<small class="text-danger">Beta</small>]
                </h4>
            </div>
            <div class="card-body">
                <p>This form allows you to execute Laravel seed or factory commands directly. Since this feature is currently in beta, please ensure you understand the commands you are running to avoid any unintended consequences.</p>
    
                <div class="row">
                    <form method="POST" action="<?php echo e(route('factory.code.runner')); ?>" enctype="multipart/form-data">
                        <?php echo csrf_field(); ?>
    
                        <div class="form-group mandatory mb-3">
                            <label class="form-label">Command / Code</label>
                            <input type="text" class="form-control <?php $__errorArgs = ['code'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?> is-invalid <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>" placeholder="Code" name="code" id="code" value="<?php echo e(old('code')); ?>"/>
                            <small class="form-text text-muted">* This feature is still in beta, so be sure you know what you're doing!</small>
                            <?php $__errorArgs = ['code'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                                <span class="invalid-feedback" role="alert">
                                    <strong><?php echo e($message); ?></strong>
                                </span>
                            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>

                            <div class="my-2">
                                <h6>Current Supported Commands</h6>
                                
                                <?php $__currentLoopData = $commands; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $command): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                    <div class="code">
                                        <code><?php echo e($command); ?></code>
                                    </div>
                                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                            </div>

                            <div class="my-2">
                                <h6>Available Seeder Files</h6>
                            
                                <?php if(count($seeders) > 0): ?>
                                    <?php $__currentLoopData = $seeders; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $seeder): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                        <div class="code">
                                            <code><?php echo e($seeder); ?></code>
                                        </div>
                                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                <?php else: ?>
                                    <p>No seeder files found.</p>
                                <?php endif; ?>
                            </div>                            

                        </div>
    
                        <div class="row">
                            <div class="col-12 d-flex justify-content-end">
                                <button type="submit" class="btn btn-sm btn-primary me-1 mb-1">Run</button>
                                <a href="<?php echo e(route('dashboard')); ?>" class="btn btn-sm btn-light-secondary me-1 mb-1">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> 
    </section>    
</div>
<?php $__env->stopSection(); ?>

<?php $__env->startPush('scripts'); ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    <?php if($errors->any()): ?>
            Swal.fire({
                toast: true,
                position: 'top-end',
                icon: 'error',
                code: 'Oops, something went wrong.',
                showConfirmButton: false,
                timer: 3000
            });
        <?php endif; ?>

        <?php if(session('success')): ?>
            Swal.fire({
                toast: true,
                position: 'top-end',
                icon: 'success',
                code: '<?php echo e(session('success')); ?>',
                showConfirmButton: false,
                timer: 3000
            });
        <?php endif; ?>
</script>
<?php $__env->stopPush(); ?>
<?php echo $__env->make('template.main', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Users\lanas\Documents\Codelabs\Laravel\personal-blog-laravel-10\resources\views\backend\developer\index.blade.php ENDPATH**/ ?>